apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: go-shssawfk-gitops
  description: This is GitOps manifest for go-shssawfk   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=go-shssawfk
    backstage.io/kubernetes-id: go-shssawfk 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: go-shssawfk
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:go-shssawfk
